version: "3.0"
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.8
    volumes:
      - ../../../../terraform/src:/terraform
    env_file:
      - .env
    working_dir: /terraform
    entrypoint: ash
    tty: true